#+TITLE: termsauce
#+AUTHOR: Chef
#+DATE: <2025-02-17 Mon>
#+DESCRIPTION: 

* Table of Contents :toc:
- [[#whats-cookin][What's cookin'?]]
  - [[#1-fortune-cookie-for-your-terminal][1. Fortune cookie for your terminal]]
  - [[#2-soyfetch---a-simple-fetch-script][2. Soyfetch - a simple fetch script]]
- [[#ingredients-needed][Ingredients needed]]
- [[#how-to-run-the-scripts][How to run the scripts]]

* What's cookin'?
This repo serves two simple scripts to make your terminal less boring. Made by Chef(chefxor).
 
** 1. Fortune cookie for your terminal
Every time you open your terminal, BAM! a random quote pops up. Motivation? Wisdom? Just nonsense? Who knows!

** 2. Soyfetch - a simple fetch script
Nothing fancy. Shows:
- OS Name
- Kernel Version
- Uptime
- Shell
- Installed Packages
- CPU & Memory Usage

* Ingredients needed
#+begin_src
lolcat
figlet
shell (bash, zsh or fish)
#+end_src

* How to run the scripts
1. Clone this repo.
2. Add them to your preferred shell as suggested below
3. Now everytime you open the shell, =fortune_cookie.sh= should run automaticallly. Use any alias for =soyfetch.sh= to display basic system info.

#+begin_src bash
# add it to your .bashrc or .zshrc. This will autospawn it everytime you open the shell
$HOME/termsauce/scripts/forture_cookie.sh

# add this as an alias in your .bashrc or .zshrc to call the ff 
alias soyfetch='$HOME/termsauce/scripts/soyfetch.sh'
#+end_src
